asus_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: asus_joint
    joint_speed: 3.0
    motor:
        id: 1
        init: 512
        min: 160
        max: 1023
